version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    environment:
      HOME: /home/builder
    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            mkdir $HOME/twrp
            cd $HOME/twrp
            # Download the TWRP Compressed Source Files from PhantomZone54's Release
            # > More on https://github.com/PhantomZone54/twrp_sources_norepo/releases/latest
            # Uncomment & Use below line If Building for Lollipop-based Devices
            # - TWRP_SOURCE="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.4.0-20201103/MinimalOmniRecovery-twrp-5.1-norepo-20201103.tzst"
            # Use below line If Building for Marshmallow-based Devices
            - TWRP_SOURCE="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.4.0-20201103/MinimalOmniRecovery-twrp-6.0-norepo-20201103.tzst"
            # Uncomment & Use below line If Building for Nougat-based Devices
            # - TWRP_SOURCE="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.4.0-20201103/MinimalOmniRecovery-twrp-7.1-norepo-20201103.tzst"
            - aria2c -x16 -s8 --console-log-level=error --summary-interval=0 "${TWRP_SOURCE}" -o twrp.tzst || wget -q --show-progress --progress=bar:force "${TWRP_SOURCE}" -O twrp.tzst
            - tar --zstd -xf twrp.tzst --directory $HOME/twrp/ && rm twrp.tzst
            # If Building for Oreo-based Devices
            # - TWRP_SOURCE1="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.4.0-20201103/MinimalOmniRecovery-twrp-8.1-norepo-20201103.tzst.aa" && TWRP_SOURCE2="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.4.0-20201103/MinimalOmniRecovery-twrp-8.1-norepo-20201103.tzst.ab"
            # If Building for Oreo-based Devices
            # - TWRP_SOURCE1="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.4.0-20201103/MinimalOmniRecovery-twrp-9.0-norepo-20201103.tzst.aa" && TWRP_SOURCE2="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.4.0-20201103/MinimalOmniRecovery-twrp-9.0-norepo-20201103.tzst.ab" && TWRP_SOURCE3="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.4.0-20201103/MinimalOmniRecovery-twrp-9.0-norepo-20201103.tzst.ac" && TWRP_SOURCE4="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.4.0-20201103/MinimalOmniRecovery-twrp-9.0-norepo-20201103.tzst.ad"
            # Then uncomment below lines to download & extract the multi-part files
            # - aria2c -x16 -s8 --console-log-level=error --summary-interval=0 "${TWRP_SOURCE1}" "${TWRP_SOURCE2}" "${TWRP_SOURCE3}" "${TWRP_SOURCE4}" || wget -q --show-progress --progress=bar:force "${TWRP_SOURCE1}" "${TWRP_SOURCE2}" "${TWRP_SOURCE3}" "${TWRP_SOURCE4}"
            # - tar --zstd -xf MinimalOmniRecovery-twrp-*.*-norepo-2020*.tzst.aa --directory $HOME/twrp/ && rm MinimalOmniRecovery*.tzst.*
      - run:
          name: Clone repositories
          command: |
            cd $HOME/twrp/
            git clone https://github.com/DraftEntree/Samsung_a03s_twrp.git device/samsung/a03s
            rm -rf bootable/recovery && git clone https://github.com/omnirom/android_bootable_recovery -b android-9.0 --depth 1 bootable/recovery
      - run:
          name: Build TWRP
          command: |
            cd $HOME/twrp/
            source build/envsetup.sh
            # Choose build flavor as "eng" or "userdebug"
            BUILD_FLAVOR="eng"
            lunch omni_a03s-eng
            make -j$(nproc --all) recoveryimage
      - run:
          name: Prepare artifacts
          command: |
            export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
            cp $HOME/twrp/out/target/product/a03s/recovery.img $HOME/twrp/TWRP-$version-a03s-$(date +"%Y%m%d")-Unofficial.img
      - store_artifacts:
          path: $HOME/twrp/
          destination: twrp-build
